### ISSUE TITLE
Couldn't read Truffle config file when running tenderly proxy

### ISSUE THREAD

**Issue by omerzam** [Tenderly/tenderly-cli#10]
I am trying to run tenderly proxy on my project and whenever I run the command tenderly proxy in my root directory where my truffle config is i get the error Couldn't read Truffle config file
the truffle-config.js is there and looks like this:
// See <http://truffleframework.com/docs/advanced/configuration>
module.exports = {
    networks: {
        development: {
            host:       "localhost",
            port:       8545,
            network_id: "*",         // Match any network id
            gasPrice:   20000000000, // Gas price used for deploys
            gas:        6721975      // Gas limit used for deploys
        },
        production: {
            host:       "localhost",
            port:       7545,
            network_id: "*",         // Match any network id
            gasPrice:   20000000000, // Gas price used for deploys
            gas:        6721975      // Gas limit used for deploys
        },
        coverage: {     // See <https://www.npmjs.com/package/solidity-coverage#network-configuration>
            host:       "localhost",
            port:       7555,            // Also in .solcover.js
            network_id: "*",             // Match any network id
            gasPrice:   0x1,             // Gas price used for deploys
            gas:        0x1fffffffffffff // Gas limit used for deploys
        }
    },
    compilers: {
        solc: {
          version: "0.4.26"  // ex:  "0.4.20". (Default: Truffle's installed solc)
        }
     },
    mocha: {
        enableTimeouts: false,
        useColors:      true,
        bail:           true,
        reporter:       "list" // See <https://mochajs.org/#reporters>
    },
    solc: {
        version: "0.4.26",
        optimizer: {
            enabled: true,
            runs:    200
        }
    }
};

**Comment by BogdanHabic** [comment]
Hey, can you re-run the proxy command with the `--debug` flag?

Also, we are slowly deprecating the `proxy` command in favor of two things:
1. We're adding the `export` command which will give you all of the tooling available at [https://dashboard.tenderly.dev/](https://dashboard.tenderly.dev/), but for local transactions
2. If you want local stack-traces we strongly suggest [Buidler](https://github.com/nomiclabs/buidler)

**Comment by omerzam** [comment]
buidler was my next go to option in if this fails i guess that's what i'll try 

either way the output of the tenderly proxy --debug command is this:

You are running version v0.5.8 of the Tenderly CLI. To update to the newest version (v0.5.9) please follow the instructions below:

curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sh

```{"file":"/go/src/github.com/tenderly/tenderly-cli/truffle/config.go:66","func":"github.com/tenderly/tenderly-cli/truffle.GetTruffleConfig","level":"debug","msg":"Trying truffle config path: /home/omerz/dev/contracts/solidity/truffle-config.js","time":"2020-03-18T14:56:17+02:00"}
{"file":"/go/src/github.com/tenderly/tenderly-cli/userError/userError.go:44","func":"github.com/tenderly/tenderly-cli/userError.LogErrorf","level":"debug","msg":"unable to upload contracts: unable to fetch config: cannot read truffle-config.js","time":"2020-03-18T14:56:17+02:00"}
{"file":"/go/src/github.com/tenderly/tenderly-cli/userError/userError.go:45","func":"github.com/tenderly/tenderly-cli/userError.LogErrorf","level":"error","msg":"Couldn't read Truffle config file","time":"2020-03-18T14:56:17+02:00"}```

**Comment by BogdanHabic** [comment]
This seems like a permission issue because if I'm not mistaken, your config file is correct.
I do strongly suggest trying Buidler as it is much more feature-rich for local stack-traces.
Once the `export` command is live, you can try that as well for the gas profiler and the rest of Tenderly tooling
