### ISSUE TITLE
install script fails without sudo 

### ISSUE THREAD

**Issue by pythonpete32** [Tenderly/tenderly-cli#13]
https://github.com/Tenderly/tenderly-cli/blob/2106a3053225ed5edc8de6cb25da26ff3ece1244/scripts/install-linux.sh#L31

the script does does not install on Ubunto 20.04 without adding sudo

**Comment by BogdanHabic** [comment]
Unfortunately to do a system-wide install on Linux needs  `sudo` on some systems. We're working on adding the option to install via `npm` as well.

Are you ok with running the installation script with `sudo`?

**Comment by pythonpete32** [comment]
I am totally fine with it, however I couldn't just prepend `sudo`, I had to download and edit the script before running it again. however `npm` would be awesome

**Comment by krzysu** [comment]
the same here, I had to modify this line in the `install-linux.sh` installation script

```
mv tenderly /usr/local/bin/
```

to

```
sudo mv tenderly /usr/bin/
```

I using Linux Subsystem on Windows

**Comment by BogdanHabic** [comment]
@krzysu Thanks for the report!

Did you try first:
```
curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh
```

We might just add that `sudo` before `sh` to the installation instructions.

**Comment by krzysu** [comment]
I didn't try that, my bin path is also different (`/usr/bin/`) but in the end I would vote for npm package that I can have tenderly-cli as part of a project and not a global installation.

**Comment by BogdanHabic** [comment]
Makes a lot of sense to do it via npm, like the rest of the CLIs in the ecosystem. Thank you for the feedback everyone 🙏

**Comment by abraham-yusuf** [comment]
Moving CLI to /usr/local/bin/
mv: cannot move 'tenderly' to '/usr/local/bin/tenderly': Permission denied
Tenderly CLI installed to:
sh: 41: tenderly: not found
New Tenderly version installed:
dev@AbrahamYusuf:~$ tenderly version
-bash: tenderly: command not found

**Comment by abraham-yusuf** [comment]
> @krzysu Thanks for the report!
> 
> Did you try first?
> 
> ```
> curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh
> ```
> 
> We might just add that `sudo` before `sh` to the installation instructions.

it's works, thanks

**Comment by nargeslein** [comment]
Hi everyone. I had the same issue running the original command but fixed it by making the whole terminal run under sudo using: 
`sudo -i`
