### ISSUE TITLE
How to delete a verification or set it private after the fact?

### ISSUE THREAD

**Issue by webhype** [Tenderly/tenderly-cli#165]
First day with Tenderly started off HORRIBLE. Found out the hard way that the `privateVerification` flag is set to `false` by default so 100s of lines of confidential development code are now leaked out to everyone on Tenderly. Off to a great start here!!

The `privateVerification` flag isn't even mentioned at this extremely important page https://docs.tenderly.co/monitoring/smart-contract-verification/verifying-contracts-using-the-tenderly-hardhat-plugin , linked to directly from this github's `readme.md`. 

One would think that one's first baby steps with Tenderly (and that's what the readme page is for, for people who know nothing yet) ... one would think that these noobs wouldn't want their development contracts to be leaked by default to absolutely _everyone???_

What is the command to "unverify" a contract? The contract is not appearing on the chain's official block explorer. Only on Tenderly. Or how to set it to private after the fact? Don't tell me there is no such command; what if we leaked passwords or private keys or other confidential information in the comments? (Not the case here but one can see how this can become a major issue in some cases).

The fact that this field is set to false by default is like the U.S. patent and trademark office leaking patents _before_ they are fully examined. Great, so all of my competitors can clone my source code and steal my ideas before I even go live, before I even go to market. 

It's insane that `privateVerification` flag is set to `false` by default!

**Comment by nvitorovic** [comment]
Hey @webhype, I’m sorry that this was your first experience with Tenderly. We’ve made the contracts private, and only you can access them now. The team has also replied in the in-app chat.

Even though the [readme](https://github.com/Tenderly/hardhat-tenderly/tree/master/packages/tenderly-hardhat#verification-modes) explains possible verification modes, you are correct that we can do a better job there (docs can always be better).

We’ll take all the necessary steps to surface the information more prominently and improve the verification process.
Thank you for your feedback and for helping us make Tenderly better for everyone.

We’re here if you need help with anything. 💜
