### ISSUE TITLE
Buidler support

### ISSUE THREAD

**Issue by abarmat** [Tenderly/tenderly-cli#19]
Hey, I see that using tenderly-cli you can push contracts from a truffle project, is it possible to do the same on a Buidler one?

Maybe as a workaround it would be great to "import verified" contracts based on the address as it's done from the web app but programatically.

**Comment by BogdanHabic** [comment]
Hey @abarmat,

It's very funny when you picked to submit this feedback! We're working right now on both [Buidler](https://github.com/nomiclabs/buidler) support and [OpenZeppelin SDK](https://github.com/OpenZeppelin/openzeppelin-sdk) as well!

It should be coming very soon to a Tenderly CLI near you 😁

**Comment by BogdanHabic** [comment]
Hey @abarmat, I wanted to let you know that ~Buidler~ Hardhat support is now live. You can read more about it [here](https://blog.tenderly.co/level-up-your-smart-contract-productivity-using-hardhat-and-tenderly/).

**Comment by abarmat** [comment]
@BogdanHabic thank you!
