### ISSUE TITLE
`tenderly init` not recognizing OpenZeppelin project

### ISSUE THREAD

**Issue by mds1** [Tenderly/tenderly-cli#22]
Create a new folder and run the following commands:

```
npm init -y
yarn add @openzeppelin/cli
yarn add --dev @openzeppelin/test-environment mocha chai
npx oz init
tenderly init
```

The result of the last command is 
```
OpenZeppelin or Truffle configuration was not detected.

Please re-run this command in a folder where at least one of the frameworks is configured.
```

I've tried adding a contract to the `contracts` folder and still get the same result, and have confirmed that I'm logged in with Tenderly. I am using Tenderly CLI v0.8.0

**Comment by Malcador** [comment]
Hey @mds1, just wanted to follow up on this. This issue has been resolved as of Tenderly CLI v0.8.2.
