### ISSUE TITLE
 Balancer Pool Token (BPT)  show no source code found

### ISSUE THREAD

**Issue by jin10086** [Tenderly/tenderly-cli#24]
https://dashboard.tenderly.co/tx/main/0x7e1c6f7010bb6e2e8a54dc37e6e4acc2dee657803b175e4f62e0bc22ce6b87dd/debugger

https://etherscan.io/address/0x461e474e594b211d41bb2ff855aa43e455d93888#code

**Comment by BogdanHabic** [comment]
Hey @jin10086, I tried the transaction and it is working fine (the code is pulled from Etherscan). Can you please check again?

**Comment by jin10086** [comment]
It's okay now, there were problems before, which is a bit strange
