### ISSUE TITLE
Can't import contract

### ISSUE THREAD

**Issue by stoplion** [Tenderly/tenderly-cli#29]
Not an CLI issue, but..

I'm trying to import the contract (by pasting in the address) 
https://etherscan.io/address/0xE9745f2c58bEe4A059F5f82A5fe846c6e8EA7D78

And it isn't working

**Comment by BogdanHabic** [comment]
Hey @stoplion,

The reason why the contract isn't automatically imported is that it is not verified on Etherscan.

You can either verify it yourself on Tenderly or Ethersacan.

Also, in the future, you can reach us much faster by clicking the chat icon in the lower right-hand corner in your Tenderly dashboard.

Bogdan
