### ISSUE TITLE
Error when pushing to tenderly (kovan network), contract that imports from @openzeppelin [Hardhat]

### ISSUE THREAD

**Issue by 0xTimepunk** [Tenderly/tenderly-cli#32]
Hi!

I receive this error when pushing to push a single contract that imports other contracts from @openzepplin, installed in node_modules) (through tenderly push)

![image](https://user-images.githubusercontent.com/45543880/115607434-e4333c80-a2dc-11eb-86cd-d42c11b66a81.png)

If I try to do this through my deployment function in hardhat (which contains the following calls):

```
    await tenderly.persistArtifacts({
      name: contractName,
      address: contractAddress
    });

    let verification = await tenderly.verify({
        name: contractName,
        address: contractAddress,
        network: targetNetwork
      })
```

It returns the following error
```
Error in hardhat-tenderly: There was an error during the request. Contract verification failed
```
What am I doing wrong?

Project is initiated at my repo with correct credentials, contract compiles and deploys to kovan correctly.

Thanks

**Comment by BogdanHabic** [comment]
Hey @0xTimepunk,

Thanks for reaching out! This can happen when some of the compiler parameters are off. I can't help out a lot without additional information like the contract address, for example.

As I see you want to keep things private, can you go to the [Tenderly Dashboard](https://dashboard.tenderly.co), click on the chat in the lower right, and send me the information there? If that works for you, we can either close this issue or report back the findings for others to see 😄 

Bogdan

**Comment by 0xTimepunk** [comment]
I think I had an issue with the hardhat compiler parameters, you were right. For some reason it was picking up solidity version 0.8.3 in the hardhat.config and after some fiddling I am now using 0.7.6 and the errors are off. Thanks for your support, if I have extra doubts I'll go into the tenderly dashboard chat

**Comment by ericnordelo** [comment]
The same thing is happening to me, so I cant use the last version of the compiler with tenderly?
