### ISSUE TITLE
Local transaction export not working

### ISSUE THREAD

**Issue by grimreaper619** [Tenderly/tenderly-cli#39]
I have ganache-cli running blockchain VM. On that I am performing truffle test and when I try to export a transaction, it gives me this error
```
Unable to get transaction rerunning information: error processing transaction: user error: %!s(<nil>), message: Missing block base fee parameter 
for block 38, london hard fork is probabbly not activated
```
Is it problem of ganache or tenderly?

**Comment by grimreaper619** [comment]
Fixed it by forking ganache on istanbul hardfork
```
ganache-cli -k istanbul
```
Then comment out london_block : 0 in yaml file (I also commented out byzantium, berlin, constantinople, petersburg also)

**Comment by BogdanHabic** [comment]
This should start working without `-k istanbul` once https://github.com/trufflesuite/ganache/pull/1135 is merged.
