### ISSUE TITLE
CLI isn't easy to install with OSX and Linux install scripts

### ISSUE THREAD

**Issue by markerdmann** [Tenderly/tenderly-cli#4]
Just a heads up, the OSX and Linux install scripts both failed for me. This is the output for the OSX installer:

```
❯ curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-macos.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1098  100  1098    0     0  10270      0 --:--:-- --:--:-- --:--:-- 10358
Installing version 0.2.6

dyld: Library not loaded: /opt/pkg/lib/libicuuc.63.dylib
  Referenced from: /opt/pkg/lib/libpsl.5.dylib
  Reason: image not found
sh: line 43:  4700 Done                    curl -s https://api.github.com/repos/Tenderly/tenderly-cli/releases/latest
      4701                       | grep "browser_download_url.*Darwin_amd64\.tar\.gz"
      4702                       | cut -d ":" -f 2,3
      4703 Broken pipe: 13         | tr -d \"
      4704 Abort trap: 6           | wget -qi -
tar: Option -f requires an argument
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
chmod: tenderly: No such file or directory
Moving CLI to /usr/local/bin/

mv: rename tenderly to /usr/local/bin/tenderly: No such file or directory
Tenderly CLI installed to: 

sh: line 38: tenderly: command not found
New Tenderly version installed:
```

On Linux I ended up downloading the latest release directly.

**Comment by markerdmann** [comment]
I'm also getting an error when I try to untar the latest Darwin release:

```
❯ tar -xvf tenderly_0.2.6_Darwin_amd64.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

**Comment by markerdmann** [comment]
Ok, looks like my issues on OSX stemmed from `wget` and `curl -O` problems. First I tried to install wget with `pkgin`, and that gave me the `Library not loaded` error above. I uninstalled wget and tried installing it from source, but that gave me the same error. Next I tried `curl -O` and got the `Unrecognized tar format` error. Finally I just downloaded the latest Darwin release with Chrome and that worked.

IIRC, on Linux (Fedora 29), the error I got from the install script was something about `-q` or `-i` not being a valid `wget` flag.

**Comment by BogdanHabic** [comment]
Hey @markerdmann, thanks for putting so much effort in installing our CLI.

Looking from what you wrote, it does seem that you are having some local issues with `curl` and `wget`.

Either way, I see this as a mistake on our side, so I'll see to refactor the installation scripts to assume the host machine has almost nothing installed other than curl.

Quick question: are you using the normal `shell`, and not `bash`?

**Comment by markerdmann** [comment]
Thanks @BogdanHabic. I'm probably not the typical user because I don't use Homebrew on OSX, so this is probably not urgent. I just wanted to give you the data about these edge cases in case it's helpful. On both OSX and Fedora I'm using `zshell`. In my Docker containers I often use `sh` because I typically use an Alpine base image.

**Comment by BogdanHabic** [comment]
An update to this: I've updated the installation scripts to only use cURL, and not wget. They should work on most systems now.

The commit can be [found here](https://github.com/Tenderly/tenderly-cli/commit/76431039af756fffc125543547e348b3ab80d1ee).
