### ISSUE TITLE
tenderly init: platform account not found Error without more explanation and 0 documentation for that error

### ISSUE THREAD

**Issue by ericnordelo** [Tenderly/tenderly-cli#55]

**Comment by BogdanHabic** [comment]
Hey,

This error isn't documented, as it is something that should never come up.

Can you please run `tenderly whoami` and tell me do you get your account information?

After that, can you please run `tenderly logout` and then `tenderly login`. I just want to check if it might be something with the generated access token.

Also, which version of the CLI are you running?

Bogdan

**Comment by ericnordelo** [comment]
I did logout, and login again, and the error is now gone for good, I was using version 1.1.5, now I'm using 1.2.1

**Comment by BogdanHabic** [comment]
The version was probably causing the issue. Glad to hear it's working now, so I'll be closing this issue.
