### ISSUE TITLE
Wrong version of @tenderly/actions when running tenderly actions init --template onboarding

### ISSUE THREAD

**Issue by htadashi** [Tenderly/tenderly-cli#62]
Running `tenderly actions init --template onboarding` on tenderly-cli v1.2.2 creates a project using @tenderly/actions 0.0.4 instead of 0.0.5

**Comment by delta003** [comment]
Thanks for reporting! This was merged but not released https://github.com/Tenderly/tenderly-cli/commit/4a6f12412763b4f140a310635cfb0a6705ef3e92

I'll release cli in a bit

We'll make this pull latest from NPM registry soon

**Comment by delta003** [comment]
It will be ready soon https://github.com/Tenderly/tenderly-cli/releases/tag/v1.3.0
