### ISSUE TITLE
TransactionReceipt missing fields

### ISSUE THREAD

**Issue by uhhhh2** [Tenderly/tenderly-cli#7]
According to https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt, a `TransactionReceipt` should contain:
- `transactionHash`
- `transactionIndex`
- **`blockHash`**
- **`blockNumber`**
- **`from`**
- **`to`**
- `cumulativeGasUsed`
- `gasUsed`
- `contractAddress`
- `logs`
- **`logsBloom`**

However, the TransactionReceipt interface used in this project (https://github.com/Tenderly/tenderly-cli/blob/master/ethereum/types.go#L69) appears to be missing the fields in **bold** above.

**Comment by nebojsa94** [comment]
Great catch! It seems we somehow missed those fields. 😔 
We’ll be pushing out an update ASAP and I’ll ping your here when it’s live!

Thanks for the heads up!

**Comment by BogdanHabic** [comment]
Just wanted to ping here that `v0.2.10`, that contains this fix has been released.
