### ISSUE TITLE
Replacing contracts instead of pushing

### ISSUE THREAD

**Issue by mvanmeerbeck** [Tenderly/tenderly-cli#70]
Hello,

It would be very useful to be able to replace a contract on tenderly that has been pushed by a newer version.
Especially on testnets when it's pretty common to deploy multiple versions for testing.
I'm using tenderly with hardhat and the process is:
- dev pushes a feature on an existing contract
- feature is merged on master
- CI pushes automatically on tenderly on multiple networks

Without the replace option, i would end up with multiple versions of the same contract

Nevertheless, awesome product!
Maxime

**Comment by Riphal** [comment]
Hello,

I'm thinking now about how that can be done, so I see 2 solutions.
1. You can use `--tag` flag and manage contract versions through tags. or
2. We can implement a flag on `tenderly push` that will delete all contacts from your project so every time you try to do `tenderly push --nameOfThatFlag` we will delete all contacts from the project then push will add the newest.

Is anything above make sense for you?

**Comment by mvanmeerbeck** [comment]
Hi!

The second option would be interesting, not perfect because i'm not sure how tenderly will react if you have alerts, actions based on contracts but i'll take it!

**Comment by Riphal** [comment]
Great, I will open PR and start working on that today so you can expect it to be implemented these days.

The only thing that comes into my mind that will be changed is to emphasize what is being removed so the command will be something like `tenderly contracts remove` and I will create a copy of `tenderly push` that now will be `tenderly contracts push`
