### ISSUE TITLE
cannot receipt output data using tenderly fork rpc

### ISSUE THREAD

**Issue by cradle0fFilth** [Tenderly/tenderly-cli#91]
This is my code 
![image](https://user-images.githubusercontent.com/64477775/175771039-e7d60ba4-02be-4844-959f-d79f7bd0fc91.png)
This is the receipt
![image](https://user-images.githubusercontent.com/64477775/175771024-307ed8a2-2113-419d-bcc3-6687ec71f65e.png)

other parameters likes "from","to"exist,but not output data of the functions,the output data exits in frontend of tenderly but i want to get it in code.

This is the frontend of the tx.
![image](https://user-images.githubusercontent.com/64477775/175771102-ea4e3808-7685-4130-86b5-0e28b2236d50.png)

**Comment by BogdanHabic** [comment]
Hey, just to be sure we can reproduce this, can you please share the full script? If you want, you can share it as a Tenderly Sandbox (https://sandbox.tenderly.co).

**Comment by cradle0fFilth** [comment]
seems this situation happens regularly when calling a read-only function .Like erc20 "balanceOf(address)","totalSupply()" etc...
here is my full code.
`const { ethers } = require("ethers");
TENDERLY_JSON_RPC_URL = "https://rpc.tenderly.co/fork/6158fd81-161b-497c-a4d5-17978b6e5e04"
contractAddress = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c";
contractABI = '[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"guy","type":"address"},{"name":"wad","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"src","type":"address"},{"name":"dst","type":"address"},{"name":"wad","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"wad","type":"uint256"}],"name":"withdraw","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"dst","type":"address"},{"name":"wad","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"deposit","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":true,"name":"guy","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":true,"name":"dst","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"dst","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"src","type":"address"},{"indexed":false,"name":"wad","type":"uint256"}],"name":"Withdrawal","type":"event"}]'
sender = "0x00233440c7d0a3924e915741538ab7ebd75cba00";
recevier = "0x2E3de07C9B8ce1a830C5E302039945b52249C8D4";

const provider = new ethers.providers.JsonRpcProvider(TENDERLY_JSON_RPC_URL);
const signer = provider.getSigner()
const contract = new ethers.Contract(contractAddress, contractABI, signer);
const allowance = ethers.utils.parseEther("100").toString(10);
const tokenAmount = ethers.utils.parseEther('0.000001').toString(10);

const tx_data = (from,to,data) => { return [{
    to: to,
    from: from,
    data: data,
    gas: ethers.utils.hexValue(300000),
    gasPrice: ethers.utils.hexValue(1),
    value: ethers.utils.hexValue(0)
    }];
}
const transact =async(data) =>{
    const call = await provider.send('eth_sendTransaction', data);
    let tx = await provider.getTransaction(call);
    let resp = await provider.getTransactionReceipt(call);
    console.log(tx);
    console.log(resp);

}

const main = async()=> {
let balanceOf = await contract.populateTransaction.balanceOf(recevier);
await transact(tx_data(recevier,contractAddress,balanceOf.data))
}

main()`

**Comment by IgorPetkovic** [comment]
The `eth_gettransactionreceipt` call is up the [specification](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactionreceipt). The output data will not be in there. If you look at the `tx` object from your code, you'll see the `data` field which has the encoded input/output.
The dashboard will display the decoded values, but we have no plans of exposing that through the RPC.
